### ISSUE TITLE
Error With Missing Semicolon

### ISSUE THREAD

**Issue by JasonBock** [JasonBock/WSharp#19]
If I put this line in the 99 bottles code (note the missing semicolon at the end):
```
2 defer(exists(4) || N(1) == N(2)) print("Take one down and pass it around,")
```
It gives this error:
```
» #loadFile NinetyNineBottles.ws
» #run

(2,79,3,80): ; expected.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at WSharp.Compiler.Text.SourceText.ToString(TextSpan span) in M:\JasonBock\Personal\Code Projects\WSharp\WSharp.Compiler\Text\SourceText.cs:line 19
   at WSharp.DiagnosticsPrinter.Print(ImmutableArray`1 diagnostics) in M:\JasonBock\Personal\Code Projects\WSharp\WSharp\DiagnosticsPrinter.cs:line 50
   at WSharp.Repl.Evaluate(Boolean showProgram, Boolean showTree, List`1 lines) in M:\JasonBock\Personal\Code Projects\WSharp\WSharp\Repl.cs:line 264
   at WSharp.Repl.EvaluateRun() in M:\JasonBock\Personal\Code Projects\WSharp\WSharp\Repl.cs:line 183
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WSharp.Repl.EvaluateMetaCommandAsync(String input) in M:\JasonBock\Personal\Code Projects\WSharp\WSharp\Repl.cs:line 160
   at WSharp.Repl.RunAsync() in M:\JasonBock\Personal\Code Projects\WSharp\WSharp\Repl.cs:line 57
```
However, the emitter is ignoring this error and emits a working program.

**Comment by JasonBock** [comment]
Here's a simplified case:
```
» 1 print("hi")
» 2 print("hi");
» #run
```
